parameters:
  tasks:
    phpcs:
      standard: Magento2
      whitelist_patterns:
        - app/code
        - app/design
      triggered_by:
        - php
        - phtml
      exclude:
        - Generic.WhiteSpace.ScopeIndent
        - Generic.Files.LineLength
    phpmd:
      exclude: ["vendor"]
      triggered_by:
        - php
        - phtml
